version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: ipecitypulse-db
    environment:
      POSTGRES_USER: ganutf
      POSTGRES_PASSWORD: 288855
      POSTGRES_DB: ipecitypulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 